data = read.csv("household_power_consumption.txt", header = TRUE, sep = ";",stringsAsFactors = FALSE, na.strings = "?")
subdata <- subset(data, Date == "1/2/2007" | Date =="2/2/2007")
DT<- strptime(paste(subdata$Date, subdata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
plot3 <- plot(DT, subdata$Sub_metering_1,type= "l", ylab = "Energy Submetering") 
lines(DT, subdata$Sub_metering_2,col="red")
lines(DT, subdata$Sub_metering_3,col="blue")
legend("topright",pch = "-",col = c("black", "red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot3
dev.copy(png,'plot3.png')
dev.off()
