data = read.csv("household_power_consumption.txt", header = TRUE, sep = ";",stringsAsFactors = FALSE, na.strings = "?")
subdata <- subset(data, Date == "1/2/2007" | Date =="2/2/2007")
old.par <- par(mfrow=c(2, 2))
DT<- strptime(paste(subdata$Date, subdata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
plota <- plot(DT, subdata$Global_active_power,type= "l", ylab = "Global Active Power (kilowatts)") 
plotb <- plot(DT, subdata$Voltage,type= "l", ylab = "Voltage") 
plotc <- plot(DT, subdata$Sub_metering_1,type= "l", ylab = "Energy Submetering") 
lines(DT, subdata$Sub_metering_2,col="red")
lines(DT, subdata$Sub_metering_3,col="blue")
legend("topright",pch = "-",col = c("black", "red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plotd <-plot(DT, subdata$Global_reactive_power,type= "l", ylab = "Global Reactive Power")
dev.copy(png,'plot4.png')
dev.off()
